/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function unpackAndSaveWebhapp(happOrWebHappPath: string, appId: string, uisDir: string, happsDir: string): Promise<void>
export type JsZomeCallSigner = ZomeCallSigner
export class ZomeCallSigner {
  constructor()
  static connect(connectionUrl: string, passphrase: string): Promise<ZomeCallSigner>
  signZomeCall(payload: Array<number>, pubKey: Array<number>): Promise<Array<number>>
}
